apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-backend-app
spec:
  replicas: 1  # 예시로 추가한 부분. 필요에 따라 조절하세요.
  selector:
    matchLabels:
      app: backend
      role: backend
      env: production
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_33b3771c24a0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
