apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-backend-app
spec:
  selector:
    matchLabels:
      app: test
      role: backend
      env: production
    template:
        metadata:
            labels:
                app: backend
        spec:
            containers:
                - name: backend
                  image: krmp-d2hub-idock.9rum.cc/dev-test/repo_33b3771c24a0
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8080